CREATE DATABASE IF NOT EXISTS pedr_db;
USE pedr_db;

CREATE TABLE IF NOT EXISTS uzivatele (
   id INT AUTO_INCREMENT PRIMARY KEY,
   jmeno VARCHAR(100) NOT NULL,
   email VARCHAR(100) NOT NULL,
   barva VARCHAR(50) NOT NULL
);
